In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [21]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5,shift=1)
for window_data in dataset:
    for val in window_data:
        print(val.numpy(),end = " ")
    print("\n-------\n")

0 1 2 3 4 
-------

1 2 3 4 5 
-------

2 3 4 5 6 
-------

3 4 5 6 7 
-------

4 5 6 7 8 
-------

5 6 7 8 9 
-------

6 7 8 9 
-------

7 8 9 
-------

8 9 
-------

9 
-------



In [25]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5,shift=1,drop_remainder = True)
for window_data in dataset:
    for val in window_data:
        print(val.numpy(),end = " ")
    print("\n-------\n")

0 1 2 3 4 
-------

1 2 3 4 5 
-------

2 3 4 5 6 
-------

3 4 5 6 7 
-------

4 5 6 7 8 
-------

5 6 7 8 9 
-------



In [35]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5,shift=1,drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
for window_data in dataset:
    print(window_data.numpy())
    print("\n-------\n")

[0 1 2 3 4]

-------

[1 2 3 4 5]

-------

[2 3 4 5 6]

-------

[3 4 5 6 7]

-------

[4 5 6 7 8]

-------

[5 6 7 8 9]

-------



In [43]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5,shift=1,drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window : (window[:-1] , window[-1:]))
for x , y in dataset:
    print(x.numpy(),y.numpy())
    print("\n-------\n")

[0 1 2 3] [4]

-------

[1 2 3 4] [5]

-------

[2 3 4 5] [6]

-------

[3 4 5 6] [7]

-------

[4 5 6 7] [8]

-------

[5 6 7 8] [9]

-------



In [50]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5,shift=1,drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window : (window[:-1] , window[-1:]))
dataset = dataset.shuffle(buffer_size = 10).batch(2)
for x , y in dataset:
    print(x.numpy(),y.numpy())
    print("\n-------\n")

[[5 6 7 8]
 [0 1 2 3]] [[9]
 [4]]

-------

[[2 3 4 5]
 [3 4 5 6]] [[6]
 [7]]

-------

[[1 2 3 4]
 [4 5 6 7]] [[5]
 [8]]

-------

